<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class TenantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'first_name' => 'Emil',
                'last_name' => 'Paduszyński',
                'email' => 'emipad04461@gmail.com',
                'phone' => '+48 123 456 789',
                'date_of_birth' => '1990-05-15',
                'city_id' => 1,
                'address' => 'ul. Słowackiego 15/3',
                'postal_code' => '80-257',
                'id_number' => '90051512345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Gdańsk',
                'id_issued_date' => '2020-03-10',
                'id_expires_date' => '2030-03-10',
                'employment_type' => 'full_time',
                'emergency_contact_name' => 'Anna Kowalska',
                'emergency_contact_phone' => '+48 987 654 321',
                'emergency_contact_relation' => 'spouse',
                'notes' => 'Preferuje mieszkania na wyższych piętrach',
                'preferences' => json_encode(['pets_allowed' => false, 'smoking' => false, 'balcony' => true]),
                'is_active' => true,
                'is_verified' => true,
                'verified_at' => Carbon::now()->subDays(30),
                'created_by' => 1,
                'managed_by' => 3,
            ],
            [
                'first_name' => 'Jan',
                'last_name' => 'Kowalski',
                'email' => 'jan.kowalski@example.com',
                'phone' => '+48 123 456 789',
                'date_of_birth' => '1990-05-15',
                'city_id' => 1,
                'address' => 'ul. Słowackiego 15/3',
                'postal_code' => '80-257',
                'id_number' => '90051512345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Gdańsk',
                'id_issued_date' => '2020-03-10',
                'id_expires_date' => '2030-03-10',
                'employment_type' => 'full_time',
                'emergency_contact_name' => 'Anna Kowalska',
                'emergency_contact_phone' => '+48 987 654 321',
                'emergency_contact_relation' => 'spouse',
                'notes' => 'Preferuje mieszkania na wyższych piętrach',
                'preferences' => json_encode(['pets_allowed' => false, 'smoking' => false, 'balcony' => true]),
                'is_active' => true,
                'is_verified' => true,
                'verified_at' => Carbon::now()->subDays(30),
                'created_by' => 1,
                'managed_by' => null,
            ],
            [
                'first_name' => 'Anna',
                'last_name' => 'Nowak',
                'email' => 'anna.nowak@example.com',
                'phone' => '+48 234 567 890',
                'date_of_birth' => '1985-12-03',
                'city_id' => 1,
                'address' => 'ul. Morska 7/12',
                'postal_code' => '80-341',
                'id_number' => '85120312345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Gdańsk',
                'id_issued_date' => '2019-08-15',
                'id_expires_date' => '2029-08-15',
                'employment_type' => 'contract',
                'emergency_contact_name' => 'Piotr Nowak',
                'emergency_contact_phone' => '+48 876 543 210',
                'emergency_contact_relation' => 'brother',
                'notes' => 'Potrzebuje miejsca parkingowego',
                'preferences' => json_encode(['pets_allowed' => true, 'smoking' => false, 'parking' => true]),
                'is_active' => true,
                'is_verified' => true,
                'verified_at' => Carbon::now()->subDays(15),
                'created_by' => 1,
                'managed_by' => null,
            ],
            [
                'first_name' => 'Michał',
                'last_name' => 'Wiśniewski',
                'email' => 'michal.wisniewski@example.com',
                'phone' => '+48 345 678 901',
                'date_of_birth' => '1992-07-22',
                'city_id' => 2,
                'address' => 'ul. Żeromskiego 33/5',
                'postal_code' => '81-372',
                'id_number' => '92072212345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Gdynia',
                'id_issued_date' => '2021-01-20',
                'id_expires_date' => '2031-01-20',
                'employment_type' => 'self_employed',
                'emergency_contact_name' => 'Katarzyna Wiśniewska',
                'emergency_contact_phone' => '+48 765 432 109',
                'emergency_contact_relation' => 'mother',
                'notes' => 'Prowadzi działalność IT z domu',
                'preferences' => json_encode(['pets_allowed' => false, 'smoking' => false, 'internet' => true, 'quiet' => true]),
                'is_active' => true,
                'is_verified' => false,
                'verified_at' => null,
                'created_by' => 1,
                'managed_by' => null,
            ],
            [
                'first_name' => 'Katarzyna',
                'last_name' => 'Zielińska',
                'email' => 'katarzyna.zielinska@example.com',
                'phone' => '+48 456 789 012',
                'date_of_birth' => '1988-03-18',
                'city_id' => 1,
                'address' => 'ul. Wrzeszcz 45/8',
                'postal_code' => '80-227',
                'id_number' => '88031812345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Gdańsk',
                'id_issued_date' => '2018-11-05',
                'id_expires_date' => '2028-11-05',
                'employment_type' => 'part_time',
                'emergency_contact_name' => 'Tomasz Zieliński',
                'emergency_contact_phone' => '+48 654 321 098',
                'emergency_contact_relation' => 'father',
                'notes' => 'Studentka medycyny, potrzebuje ciszy do nauki',
                'preferences' => json_encode(['pets_allowed' => true, 'smoking' => false, 'study_room' => true]),
                'is_active' => true,
                'is_verified' => true,
                'verified_at' => Carbon::now()->subDays(45),
                'created_by' => 1,
                'managed_by' => null,
            ],
            [
                'first_name' => 'Paweł',
                'last_name' => 'Dąbrowski',
                'email' => 'pawel.dabrowski@example.com',
                'phone' => '+48 567 890 123',
                'date_of_birth' => '1975-11-30',
                'city_id' => 3,
                'address' => 'ul. Kościuszki 12/4',
                'postal_code' => '84-230',
                'id_number' => '75113012345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Rumia',
                'id_issued_date' => '2017-06-12',
                'id_expires_date' => '2027-06-12',
                'employment_type' => 'full_time',
                'emergency_contact_name' => 'Marta Dąbrowska',
                'emergency_contact_phone' => '+48 543 210 987',
                'emergency_contact_relation' => 'wife',
                'notes' => 'Pracuje zmianowo, potrzebuje dobrej komunikacji',
                'preferences' => json_encode(['pets_allowed' => false, 'smoking' => true, 'transport' => true]),
                'is_active' => true,
                'is_verified' => true,
                'verified_at' => Carbon::now()->subDays(60),
                'created_by' => 1,
                'managed_by' => null,
            ],
            [
                'first_name' => 'Magdalena',
                'last_name' => 'Kaczmarek',
                'email' => 'magdalena.kaczmarek@example.com',
                'phone' => '+48 678 901 234',
                'date_of_birth' => '1993-09-08',
                'city_id' => 1,
                'address' => 'ul. Przymorze 78/15',
                'postal_code' => '80-557',
                'id_number' => '93090812345',
                'id_type' => 'national_id',
                'id_issued_by' => 'Urząd Miasta Gdańsk',
                'id_issued_date' => '2022-02-28',
                'id_expires_date' => '2032-02-28',
                'employment_type' => 'student',
                'emergency_contact_name' => 'Jerzy Kaczmarek',
                'emergency_contact_phone' => '+48 432 109 876',
                'emergency_contact_relation' => 'father',
                'notes' => 'Studiuje architekturę, potrzebuje dużo miejsca na projekty',
                'preferences' => json_encode(['pets_allowed' => true, 'smoking' => false, 'large_space' => true, 'natural_light' => true]),
                'is_active' => true,
                'is_verified' => false,
                'verified_at' => null,
                'created_by' => 1,
                'managed_by' => null,
            ],
        ];

        $now = Carbon::now();

        foreach ($items as &$item) {
            $item['uuid'] = Str::uuid()->toString();
            $item['created_at'] = $now;
            $item['updated_at'] = $now;
        }

        DB::table('tenants')->insert($items);
    }
}
